#' Calculate design effect from weights
#'
#' Estimates the variance inflation caused by unequal weighting. With only
#' \code{weights}, returns the Kish (1992) estimator, which assumes no
#' correlation between weights and outcomes. When \code{outcome}, \code{data},
#' and \code{target} are all supplied, returns the Henry & Valliant (2015)
#' estimator, which accounts for correlation between the outcome and the
#' calibration auxiliary variables used in raking.
#'
#' @param weights A numeric vector of weights, or a data frame containing a
#'   column named \code{"weights"} or one of the automatic column names
#'   generated by \code{\link{harvest}}.
#' @param outcome Optional. A numeric vector of outcome values, equal in
#'   length to \code{weights}. If NULL (default), returns the Kish (1992)
#'   estimator. If supplied along with \code{data} and \code{target}, returns
#'   the Henry & Valliant (2015) estimator.
#' @param data Optional. The data frame supplied to \code{\link{harvest}}
#'   when generating \code{weights}. Required together with \code{target} for
#'   Henry & Valliant (2015). Must not be NULL if \code{target} is given.
#' @param target Optional. The target proportions list supplied to
#'   \code{\link{harvest}} when generating \code{weights}. Required together
#'   with \code{data} for Henry & Valliant (2015). Must not be NULL if
#'   \code{data} is given.
#' @return A single numeric design effect value.
#'
#' @references
#' Kish, L. (1992). Weighting for unequal Pi. \emph{Journal of Official
#'   Statistics}, 8(2), 183--200.
#'
#' Henry, K.A. & Valliant, R. (2015). A design effect measure for calibration
#'   weighting in single-stage samples. \emph{Survey Methodology}, 41(2),
#'   315--331.
#'
#' Spencer, B.D. (2000). An approximate design effect for unequal weighting
#'   when measurements may correlate with selection probabilities.
#'   \emph{Survey Methodology}, 26(2), 137--138. Note: Spencer (2000) assumes
#'   design weights satisfying w_i = 1/(n * P_i). Raking/calibration weights
#'   do not satisfy this identity; this estimator is not appropriate for use
#'   with raking weights.
#'
#' @importFrom stats lm var
#' @export
design_effect = function(weights, outcome = NULL, data = NULL, target = NULL) {
  if(is.data.frame(weights)) {
    cand_weights = c("weights", ".weights_autumn", paste0(".weights_autumn", 1:10))
    weight_var = cand_weights[which(cand_weights %in% colnames(weights))[1]]
    if(is.na(weight_var)) {
      stop("Error: design_effect requires a `weights` argument. If the ",
           "argument specified is a data frame, it must contain a column ",
           "named weights. Please specify weights directly or correct data ",
           "frame.")
    }

    weights = weights[[weight_var]]
  }

  # Kish (1992) estimator — n * sum(w^2) / (sum(w))^2
  kish_estimate = length(weights) * sum(weights^2) / sum(weights)^2

  # Case: outcome NULL, data and/or target given — warn and return Kish
  if(is.null(outcome) && (!is.null(data) || !is.null(target))) {
    warning("Henry & Valliant (2015) design effect requires `outcome`. ",
            "`data` and `target` are ignored when `outcome` is NULL. ",
            "Returning Kish (1992) design effect.")
    return(kish_estimate)
  }

  # Case: no outcome — return Kish
  if(is.null(outcome)) return(kish_estimate)

  # From here: outcome is given
  # Basic error checking on outcome
  if(length(outcome) != length(weights)) {
    stop("Error: The provided outcome is not equal in length to the provided ",
         "weights.")
  }

  if(!is.numeric(outcome)) {
    stop("Error: The provided outcome must be numeric.")
  }

  # Case: outcome given, but data or target is missing (not both together)
  if(is.null(data) && is.null(target)) {
    warning("Henry & Valliant (2015) design effect requires both `data` (the ",
            "raking data frame) and `target` (the target proportions list ",
            "used in harvest()) to compute GREG residuals. Falling back to ",
            "Kish (1992) estimator, which assumes no correlation between ",
            "outcome and calibration variables.")
    return(kish_estimate)
  }

  if(is.null(data) || is.null(target)) {
    stop("Error: `data` and `target` must be supplied together. Provide both ",
         "or neither. To compute Henry & Valliant (2015) design effect, both ",
         "are required.")
  }

  # Henry & Valliant (2015): deff_H = (1 - R^2_w) * deff_K
  # Pre-flight validation
  missing_cols = names(target)[!names(target) %in% colnames(data)]
  if(length(missing_cols) > 0) {
    stop("Henry & Valliant (2015) design effect: the following target ",
         "variables are not columns in `data`: ",
         paste(missing_cols, collapse = ", "))
  }

  if(any(is.na(outcome))) {
    stop("Henry design effect requires no NA values in `outcome`.")
  }

  if(!is.finite(var(outcome)) || var(outcome) == 0) {
    stop("Henry design effect requires non-constant `outcome`; ",
         "var(outcome) == 0 yields undefined R\u00b2.")
  }

  # Force factor on all calibration vars (ensures dummy-coding, not linear
  # treatment of numeric-coded categories)
  X_df = as.data.frame(data[, names(target), drop = FALSE])
  X_df[] = lapply(X_df, function(x) if(!is.factor(x)) factor(x) else x)

  # Weighted regression. summary(lm(..., weights = w))$r.squared returns
  # weighted R^2: 1 - SS_res_w / SS_tot_w, where SS = sum(w_i * residual_i^2)
  fit = lm(outcome ~ ., data = X_df, weights = weights)
  R2 = summary(fit)$r.squared

  (1 - R2) * kish_estimate
}

#' Calculate effective sample size from weights
#'
#' Returns the effective sample size implied by the supplied weights. Because
#' weighting inflates variance, the effective sample size of a weighted sample
#' is less than the nominal sample size.
#'
#' @param weights A numeric vector of weights, or a data frame containing a
#'   weight column. See \code{\link{design_effect}} for details.
#' @param outcome Optional. A numeric outcome vector. See
#'   \code{\link{design_effect}}.
#' @param data Optional. The data frame supplied to \code{\link{harvest}}.
#'   See \code{\link{design_effect}}.
#' @param target Optional. The target proportions list supplied to
#'   \code{\link{harvest}}. See \code{\link{design_effect}}.
#' @return A numeric effective sample size (may be non-integer).
#' @references
#' Henry, K.A. & Valliant, R. (2015). A design effect measure for calibration
#'   weighting in single-stage samples. \emph{Survey Methodology}, 41(2),
#'   315--331.
#' @export
effective_sample_size = function(weights, outcome = NULL,
                                 data = NULL, target = NULL) {
  if(is.data.frame(weights)) {
    # Legacy data-frame path: data and target must still be forwarded
    return(nrow(weights) / design_effect(weights, outcome,
                                         data = data, target = target))
  }

  return(length(weights) / design_effect(weights, outcome,
                                          data = data, target = target))
}
